# permissions for end users to view document-hostings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: document-hosting-viewer-role
rules:
- apiGroups:
  - hosting.otc-service.com
  resources:
  - document-hostings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hosting.otc-service.com
  resources:
  - document-hostings/status
  verbs:
  - get
